"""$(d)

Revision ID: 3fe65fd84aa6
Revises: d4ed96ab7ca5
Create Date: 2024-05-20 21:31:35.256040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe65fd84aa6'
down_revision: Union[str, None] = 'd4ed96ab7ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
