"""$(d)

Revision ID: b242948d796e
Revises: 314b0c98015f
Create Date: 2024-05-20 20:44:06.500187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b242948d796e'
down_revision: Union[str, None] = '314b0c98015f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('catergoria_id', sa.Integer(), nullable=False))
    op.drop_constraint('atletas_categoria_id_fkey', 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'categorias', ['catergoria_id'], ['pk_id'])
    op.drop_column('atletas', 'categoria_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key('atletas_categoria_id_fkey', 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    op.drop_column('atletas', 'catergoria_id')
    # ### end Alembic commands ###
